AWSTemplateFormatVersion: "2010-09-09"
Description: Deoploy a multi-tier application architecture using nested CloudFormation stacks.
Metadata:
  Comment: This is a group project for course INFOSYS 735 group assessment2
  Owner: Group 15

Parameters:
  namePrefix:
    Type: String
    Default: AnyGroup
    Description: Prefix for resource names

  repositoryUrl:
    Type: String
    #GitURL: https://raw.githubusercontent.com/Steven-lei/INFOSYS735-groupassessment2/main
    #BucketURL: https://anygroup-templates.s3.us-east-1.amazonaws.com
    Default: https://anygroup-templates.s3.us-east-1.amazonaws.com
    Description: S3 bucket URL where the nested stack templates are stored, such as https://s3.amazonaws.com/your-bucket-name

Resources:
  StaticWebsite:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${repositoryUrl}/templates/s3_staticwebsite.yaml"
      Parameters:
        namePrefix: !Ref namePrefix

Outputs:
  WebsiteURL:
    Value: !GetAtt StaticWebsite.Outputs.WebsiteURL
    Description: The URL of the static website
