AWSTemplateFormatVersion: "2010-09-09"
Description:
  Create an application Load balancer using specific target group, using the certificate from ACM for HTTPS listener, and
  update the Route53 A record to point to the ALB after creation
Metadata:
  Comment: This is a group project for course INFOSYS 735 group assessment2
  Owner: Group 15

Parameters:
  namePrefix:
    Type: String
    Default: AnyGroup
    Description: Prefix for resource names
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of Subnet IDs where the load balancer will be created
  SecurityGroupId:
    Type: String
    Description: Security Group ID for the Load Balancer
  TargetGroupArn:
    Type: String
    Description: ARN of the target group to register with the load balancer
  HostedZoneId:
    Type: String
    Description: Route53 Hosted Zone ID for the domain
  CertificateArn:
    Type: String
    Description: ACM Certificate ARN for HTTPS listener
Resources:
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${namePrefix}-ALB"
      Subnets: !Ref SubnetIds
      SecurityGroups:
        - !Ref SecurityGroupId
      Scheme: internet-facing

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroupArn
      # DefaultActions:
      #   - Type: redirect
      #     RedirectConfig:
      #       Protocol: HTTPS
      #       Port: "443"
      #       StatusCode: HTTP_301

  ALBHttpsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref CertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroupArn

  # Update the A record to point to the ALB
  AliasRecord:
    Type: AWS::Route53::RecordSet
    DependsOn: ApplicationLoadBalancer
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "${namePrefix}.theflower.co.nz" # the record name
      Type: A # A record is used for alias to ALB
      AliasTarget:
        DNSName: !GetAtt ApplicationLoadBalancer.DNSName
        HostedZoneId: !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID
        EvaluateTargetHealth: false
Outputs:
  LoadBalancerDNSName:
    Description: DNS Name of the Load Balancer
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: !Sub "${AWS::StackName}-LoadBalancerDNSName"
  LoadBalancerArn:
    Description: ARN of the Load Balancer
    Value: !Ref ApplicationLoadBalancer
    Export:
      Name: !Sub "${AWS::StackName}-LoadBalancerArn"
  PublicDNSName:
    Description: DNS Name of the Load Balancer
    Value: !Sub "https://${namePrefix}.theflower.co.nz" # the subdomain name to access the ALB
    Export:
      Name: !Sub "${namePrefix}-DNSName"
