---
AWSTemplateFormatVersion: "2010-09-09"
Description: |
  create a targetGroup and then create an AutoScalingGroup using that targetGroup.
  create a SNS topic 
  send email notification when autoscaling activity occurs.
Metadata:
  Comment: "This is a group project for course INFOSYS 735 group assessment2"
  Owner: "Group 15"
Parameters:
  namePrefix:
    Type: String
    Default: AnyGroup
    Description: Prefix for resource names

  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where the target group will be created

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of Subnet IDs where the target group will be used

  LaunchTemplateId:
    Type: String
    Description: ID of the launch template to be used for the Auto Scaling group

  LaunchTemplateVersion:
    Type: String
    Description: Version of the launch template to be used for the Auto Scaling group

  Email:
    Type: String
    Description: Email addresses for SNS notification
    Default: "leizhengwen@126.com"
Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${namePrefix}-SNS-Topic"

  SNSTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref SNSTopic
      Protocol: email
      Endpoint: !Ref Email

  AppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${namePrefix}-AppTG"
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VPCId
      HealthCheckPath: /healthcheck.html
      HealthCheckIntervalSeconds: 10
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      TargetType: instance
      Tags:
        - Key: Name
          Value: !Sub "${namePrefix}-AppTargetGroup"

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub "${namePrefix}-AutoScalingGroup"
      VPCZoneIdentifier: !Ref SubnetIds
      TargetGroupARNs:
        - !Ref AppTargetGroup
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplateId
        Version: !Ref LaunchTemplateVersion
      MinSize: 2
      MaxSize: 6
      DesiredCapacity: 2
      HealthCheckGracePeriod: 30
      Tags:
        - Key: Name
          Value: !Sub "${namePrefix}-AutoScalingInstance"
          PropagateAtLaunch: true
      NotificationConfigurations:
        - TopicARN: !Ref SNSTopic
          NotificationTypes:
            - autoscaling:EC2_INSTANCE_LAUNCH
            - autoscaling:EC2_INSTANCE_TERMINATE
            - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
            - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
  TrackingPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub "${namePrefix}-TrackingPolicy"
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: 25.0
        DisableScaleIn: false

  # StepPolicy:
  #   Type: AWS::AutoScaling::ScalingPolicy
  #   Properties:
  #     AutoScalingGroupName: !Ref AutoScalingGroup
  #     PolicyType: StepScaling
  #     AdjustmentType: ChangeInCapacity
  #     StepAdjustments:
  #       - MetricIntervalLowerBound: 70
  #         ScalingAdjustment: 1 # CPU > 70%，add 1 instance
  #       - MetricIntervalUpperBound: 30
  #         ScalingAdjustment: -1 # CPU < 30%，remove 1 instance
  #     Cooldown: 60
Outputs:
  TargetGroupARN:
    Description: The ARN of the target group
    Value: !Ref AppTargetGroup
    Export:
      Name: !Sub "${AWS::StackName}-AppTargetGroupARN"
