AWSTemplateFormatVersion: "2010-09-09"
Description: Create DBSubnetGroup, RDS instance for Oracle, and Save the credentials in Secrets Manager.
Metadata:
  Comment: This is a group project for course INFOSYS 735 group assessment2
  Owner: Group 15
Parameters:
  #Prefix for resource names
  namePrefix:
    Type: String
    Default: AnyGroup
    Description: Prefix for resource names

  #SubnetIds for DB Subnet Group
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of Subnet IDs for the DB Subnet Group

  SecurityGroupId:
    Type: String
    Description: Security Group ID for the RDS instance

  #DB username
  DBUsername:
    Type: String
    Default: dbadmin
    Description: Username for the RDS instance

  #DB password
  DBPassword:
    Type: String
    NoEcho: true
    Description: Password for the RDS instance
Resources:
  #Create secret in Secrets Manager to store RDS credentials, dbhost, dbport, dbname,and dburl will be added automatically
  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${namePrefix}-RDSSecret
      Description: Secret for RDS instance credentials
      SecretString: !Sub |
        {
          "username": "${DBUsername}",
          "password": "${DBPassword}"
        }
      Tags:
        - Key: Name
          Value: !Sub ${namePrefix}-RDSSecret
  #Create DB Subnet Group for RDS instance
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS instance
      SubnetIds: !Ref SubnetIds
      Tags:
        - Key: Name
          Value: !Sub ${namePrefix}-DBSubnetGroup
  #Create RDS instance for Oracle
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub ${namePrefix}-RDSInstance
      StorageType: gp2
      AllocatedStorage: "20"
      DBInstanceClass: db.t3.small
      Engine: oracle-se2
      EngineVersion: 19.0.0.0.ru-2025-07.rur-2025-07.r1
      LicenseModel: license-included
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      StorageEncrypted: true
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref SecurityGroupId
      MultiAZ: false
      PubliclyAccessible: false # RDS instance is not publicly accessible
      DeletionProtection: false
      #BackupRetentionPeriod: 7 # Enable automated backups with a retention period of 7 days
      #PreferredBackupWindow: "03:00-04:00" # Set preferred backup window
      #PreferredMaintenanceWindow: "sun:05:00-sun:06:00" # Set preferred maintenance window
      Tags:
        - Key: Name
          Value: !Sub ${namePrefix}-RDSInstance

Outputs:
  RDSEndpoint:
    Description: RDS endpoint address
    Value: !GetAtt RDSInstance.Endpoint.Address
    Export:
      Name: !Sub ${namePrefix}-RDSEndpoint

  RDSPort:
    Description: RDS endpoint port
    Value: !GetAtt RDSInstance.Endpoint.Port
    Export:
      Name: !Sub ${namePrefix}-RDSPort
