AWSTemplateFormatVersion: "2010-09-09"
Description: Create a launchtemplate using existing AMI
Metadata:
  Comment: This is a group project for course INFOSYS 735 group assessment2
  Owner: Group 15
Parameters:
  namePrefix:
    Type: String
    Default: AnyGroup
    Description: Prefix for resource names
  SecurityGroupId:
    Type: String
    Description: Security Group ID for the EC2 instances
  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
  InstanceType:
    Description: Enter t2.micro, t2.small, t3.micro, and t3.small, default is t2.small.
    Type: String
    Default: t2.small
    AllowedValues:
      - t2.micro
      - t2.small
      - t3.micro
      - t3.small
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
  EC2InstanceProfile:
    Type: String
    Description: IAM Instance Profile Name for the EC2 instances
Resources:
  WebLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub "${AWS::StackName}-WebLaunchTemplate"
      LaunchTemplateData:
        ImageId: !Ref LatestAmiId
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        SecurityGroupIds:
          - !Ref SecurityGroupId
        IamInstanceProfile:
          Name: !Ref EC2InstanceProfile
        #IamInstanceProfile: !Ref EC2InstanceProfile
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            yum install -y httpd
            systemctl start httpd
            systemctl enable httpd
            echo "<html><h1>Welcome to EC2 with Private IP: $(curl http://169.254.169.254/latest/meta-data/local-ipv4)</h1></html>" > /var/www/html/myipaddress.html
            echo "<html>healthcheck ok</html>" > /var/www/html/healthcheck.html
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: WebServerInstance
          - ResourceType: volume
            Tags:
              - Key: Name
                Value: WebServerVolume
Outputs:
  LaunchTemplateId:
    Description: The ID of the launch template
    Value: !Ref WebLaunchTemplate
    Export:
      Name: !Sub "${AWS::StackName}-WebLaunchTemplateId"
  LaunchTemplateVersion:
    Description: The version of the launch template
    Value: !GetAtt WebLaunchTemplate.LatestVersionNumber
    Export:
      Name: !Sub "${AWS::StackName}-WebLaunchTemplateVersion"
  LaunchTemplateARN:
    Description: The ARN of the launch template
    Value: !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:launch-template/${WebLaunchTemplate}"
    Export:
      Name: !Sub "${AWS::StackName}-WebLaunchTemplateARN"
