AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Create NACL rules for subnets
  PublicSubnets: Allowing HTTP/HTTPS from anywhere, Allowing SSH only from local IP
  AppSubnets: Allowing HTTP/HTTPS from PublicSubnets
  DBSubnets: Allowing DB port(Oracle:1521, MySQL:3306) from AppSubnets

Metadata:
  Comment: This is a group project for course INFOSYS 735 group assessment2
  Owner: Group 15
Parameters:
  namePrefix:
    Type: String
    Description: Enter the name prefix for the stack.
    Default: "Anygroup"
  VpcId:
    Description: Enter the VPC id
    Type: String
    AllowedPattern: "vpc-[a-z0-9]*"
    ConstraintDescription: "Must be a valid VPC ID"
  #List of the public subnets
  PublicSubnets:
    Description: Select the public subnets
    Type: List<AWS::EC2::Subnet::Id>
    ConstraintDescription: "Must be a valid subnet ID"
  #List of the private subnets
  PrivateSubnets:
    Description: Select the private subnets
    Type: List<AWS::EC2::Subnet::Id>
    ConstraintDescription: "Must be a valid subnet ID"
  #List of the db subnets
  DBSubnets:
    Description: Select the DB subnets
    Type: List<AWS::EC2::Subnet::Id>
    ConstraintDescription: "Must be a valid subnet ID"
Resources:
  PublicNACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId:
        Ref: VpcId
      Tags:
        - Key: Name
          Value: !Sub "${namePrefix}-PublicNACL"
  AppNACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId:
        Ref: VpcId
      Tags:
        - Key: Name
          Value: !Sub "${namePrefix}-AppNACL"
  DBNACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId:
        Ref: VpcId
      Tags:
        - Key: Name
          Value: !Sub "${namePrefix}-DBNACL"

  ################################################## FOR PUBLIC SUBNETS ########################################
  # Inbound rules
  # Allow HTTP (80)
  PublicNACLInboundHTTP:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PublicNACL
      RuleNumber: 100
      Protocol: 6 # TCP
      RuleAction: allow
      Egress: false
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 80
        To: 80

  # Allow HTTPS (443)
  PublicNACLInboundHTTPS:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PublicNACL
      RuleNumber: 110
      Protocol: 6 # TCP
      RuleAction: allow
      Egress: false
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 443
        To: 443

  # Allow SSH (22) if needed
  PublicNACLInboundSSH:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PublicNACL
      RuleNumber: 120
      Protocol: 6 # TCP
      RuleAction: allow
      Egress: false
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 22
        To: 22

  # Outbound rules
  # Allow all outbound
  PublicNACLOutboundAllowAll:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PublicNACL
      RuleNumber: 100
      Protocol: -1
      RuleAction: allow
      Egress: true
      CidrBlock: 0.0.0.0/0

  PublicSubnetANaclAssociate:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref PublicNACL
      SubnetId: ! Select[0, !Ref PublicSubnets]

  PublicSubnetBNaclAssociate:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref PublicNACL
      SubnetId: ! Select[1, !Ref PublicSubnets]

  ######################################################## FOR APP SUBNETS ########################################
  # Inbound rules
  # Allow HTTP (80)
  AppNACLInboundHTTP:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref AppNACL
      RuleNumber: 100
      Protocol: 6 # TCP
      RuleAction: allow
      Egress: false
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 80
        To: 80

  # Outbound rules
  # Allow all outbound
  AppNACLOutboundAllowAll:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref AppNACL
      RuleNumber: 100
      Protocol: -1
      RuleAction: allow
      Egress: true
      CidrBlock: 0.0.0.0/0

  AppSubnetANaclAssociate:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref AppNACL
      SubnetId: ! Select[0, !Ref AppSubnets]
  AppSubnetBNaclAssociate:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref AppNACL
      SubnetId: ! Select[1, !Ref AppSubnets]

  ####################################################### FOR DB SUBNETS ###############################################
  # Inbound rules
  # Allow ORACLE,MYSQL (1521,3306)
  DBNACLInboundHTTPOracle:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref DBNACL
      RuleNumber: 100
      Protocol: 6 # TCP
      RuleAction: allow
      Egress: false
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 1521
        To: 1521

  DBNACLInboundHTTPMySql:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref DBNACL
      RuleNumber: 110
      Protocol: 6 # TCP
      RuleAction: allow
      Egress: false
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 3306
        To: 3306
  # Allow all outbound
  DBNACLOutboundAllowAll:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref DBNACL
      RuleNumber: 100
      Protocol: -1
      RuleAction: allow
      Egress: true
      CidrBlock: 0.0.0.0/0
  DBSubnetANaclAssociate:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref DBNACL
      SubnetId: ! Select[0, !Ref DBSubnets]
  DBSubnetBNaclAssociate:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref DBNACL
      SubnetId: ! Select[1, !Ref DBSubnets]
