AWSTemplateFormatVersion: "2010-09-09"
Description: create a WebServer in the specified subnet
Metadata:
  Comment: "This is a group project for course INFOSYS 735 group assessment2"
  Owner: "Group 15"

Parameters:
  namePrefix:
    Type: String
    Default: AnyGroup
    Description: Prefix for resource names
  LatestAmiId:
    Type: String
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID where the EC2 instance will be launched
  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: One or more SecurityGroup IDs to associate with the EC2 instance
  InstanceType:
    Description: Enter t2.micro, t2.small, t3.micro, and t3.small, default is t2.small.
    Type: String
    Default: t2.small
    AllowedValues:
      - t2.micro
      - t2.small
      - t3.micro
      - t3.small
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
  EC2InstanceProfile:
    Type: String
    Description: IAM Instance Profile Name for the EC2 instances
Mappings:
  RegionMap:
    us-east-1:
      "keypair": "group15-us-east-1"
    us-west-2:
      "keypair": "group15-us-west-2"
Resources:
  WebInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName #!FindInMap [RegionMap, !Ref "AWS::Region", keypair]
      ImageId: !Ref LatestAmiId
      IamInstanceProfile: !Ref EC2InstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref SubnetId
          GroupSet: !Ref SecurityGroupIds
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # ====== System update ======
          yum update -y

          # ====== Install PHP 8.2, Apache, MySQL client ======
          amazon-linux-extras enable php8.2
          yum install php-cli php-fpm php-mysqlnd php-json php-common php-mbstring php-curl php-xml git unzip httpd mariadb105 -y

          # ====== Create Default Page ======
          echo "<html><h1>Welcome to EC2 with Private IP: $(curl http://169.254.169.254/latest/meta-data/local-ipv4)</h1></html>" > /var/www/html/myipaddress.html
          echo "<html>healthcheck ok</html>" > /var/www/html/healthcheck.html

          # ====== Enable & start Apache ======
          systemctl enable httpd
          systemctl start httpd

          # ====== Install Composer ======
          cd /tmp
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          composer --version

          # ====== Deploy application ======
          cd /home/ec2-user
          git clone --no-checkout https://github.com/Steven-lei/Cafe.git
          cd Cafe
          git sparse-checkout init --cone
          git sparse-checkout set cafe_secrets
          git checkout

          # Copy app files to Apache root
          mkdir -p /var/www/html/cafe
          cp -r cafe_secrets/* /var/www/html/cafe/

          # ====== Install AWS SDK for PHP ======
          cd /var/www/html/cafe 
          php /usr/local/bin/composer require aws/aws-sdk-php

          # ====== Permissions ======
          chown -R apache:apache /var/www/html/cafe
          chmod -R 755 /var/www/html/cafe

          # ====== Restart Apache ======
          systemctl restart httpd

      Tags:
        - Key: Name
          Value: !Sub ${namePrefix}-WebInstance
Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref WebInstance
  InstancePublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt WebInstance.PublicIp
  InstancePrivateIP:
    Description: Private IP address of the EC2 instance
    Value: !GetAtt WebInstance.PrivateIp
  InstancePublicDNS:
    Description: Public DNS name of the EC2 instance
    Value: !GetAtt WebInstance.PublicDnsName
